### ISSUE TITLE
Using a key that is bound to Find Me deletes huts in Minecolonies

### ISSUE THREAD

**Issue by kezmodius** [Buuz135/FindMe#40]
I'm playing ATM9. Within Minecolonies I open the Postbox interface, I search an item (rack in this case), I click in box to input the number I want, I hear a hiss, click request, nothing happens. Then the block (Postbox )has lost its building along with an adjacent hutblock (the university). With experimenting we figured out that it was due to my using the '1' on the numpad to input the number. Apparently it was linked to Find Me - Pull 1 stack from nearby inventories. I have no idea why it deleted the hutblocks and the nearby hutblocks but it stopped happening when I unbound the key.

findme-3.2.0-forge.jar

**Comment by uecasm** [comment]
I think the main unexpected thing is that when a non-inventory GUI is open and typing a number into an input box, the hotkey is triggered, when it seems like it is intended to only operate in inventories.

The building deletion itself is something on the Minecolonies side, because it's reacting to the BreakEvent.  The overreaction is probably a bug on our end, but this seems like an odd way to check if an inventory is accessible.
